export const TASTE_GENRE_GROUPS = [
  {
    key: 'movie',
    label: 'Movies',
    genres: [
      'Action',
      'Adventure',
      'Animation',
      'Comedy',
      'Drama',
      'Dramedy',
      'Documentary',
      'Fantasy',
      'Ghost stories',
      'Horror',
      'Mystery',
      'Romance',
      'Sci-Fi',
      'Superhero',
      'Thriller',
    ],
  },
  {
    key: 'tv',
    label: 'TV',
    genres: [
      'Animated series',
      'Comedy',
      'Crime',
      'Docuseries',
      'Drama',
      'Dramedy',
      'Fantasy',
      'Food & travel',
      'Mystery',
      'Reality',
      'Sci-Fi',
      'Superhero',
      'Thriller',
    ],
  },
  {
    key: 'book',
    label: 'Books',
    genres: [
      'Biography',
      'Book club fiction',
      'Fantasy',
      'Historical fiction',
      'Horror',
      'Literary fiction',
      'Memoir',
      'Mystery',
      'Nonfiction',
      'Romance',
      'Sci-Fi',
      'Short stories',
      'Thriller',
    ],
  },
  {
    key: 'album',
    label: 'Music',
    genres: [
      'Alternative',
      'Country',
      'Electronic',
      'Folk',
      'Hip-Hop',
      'Indie',
      'Jazz',
      'Pop',
      'R&B',
      'Rock',
      'Singer-songwriter',
      'Soul',
    ],
  },
  {
    key: 'game',
    label: 'Games',
    genres: [
      'Adventure',
      'Arcade',
      'Fighting',
      'Indie',
      'Platform',
      'Puzzle',
      'RPG',
      'Shooter',
      'Simulator',
      'Sport',
      'Strategy',
    ],
  },
]

